### PR TITLE
improved intuitiveness & added example code

### PR DESCRIPTION
**Pull request by JohnSt99**
Added examples as well as key commands to setting up everything in order to run the test commands

### CODE REVIEW

**Comment by JohnSt99** [comment]
This request is correct and the final, im sorry but i hadn't used merge requests in the past.

**Comment by benediamond** [comment]
many thanks for these contributions. i've made some small touchups, in 943a902, please take a look and if it looks good i'll merge.

a couple small questions:

- i noticed you used port 9545. but by default, my `ganache-cli` listens on 8545. am I missing something?
- when I execute `ZSC.deployed();`, i get the following traceback:
```javascript
> (node:52653) UnhandledPromiseRejectionWarning: Error: connection not open on send()
    at Object.ConnectionError (/Users/benjamindiamond/anonymous-zether/node_modules/web3-core-helpers/src/errors.js:72:23)
    at Object.ConnectionNotOpenError (/Users/benjamindiamond/anonymous-zether/node_modules/web3-core-helpers/src/errors.js:51:21)
    at WebsocketProvider.send (/Users/benjamindiamond/anonymous-zether/node_modules/web3-providers-ws/src/index.js:323:33)
    at RequestManager.send (/Users/benjamindiamond/anonymous-zether/packages/protocol/node_modules/web3-core-requestmanager/src/index.js:162:66)
    at sendRequest (/Users/benjamindiamond/anonymous-zether/packages/protocol/node_modules/web3-core-method/src/index.js:750:42)
    at Net.send [as getId] (/Users/benjamindiamond/anonymous-zether/packages/protocol/node_modules/web3-core-method/src/index.js:784:13)
    at Web3InterfaceAdapter.getNetworkId (/Users/benjamindiamond/anonymous-zether/packages/protocol/node_modules/@truffle/interface-adapter/lib/adapter/web3/index.ts:22:30)
    at Function.detectNetwork (/Users/benjamindiamond/anonymous-zether/packages/protocol/node_modules/@truffle/contract/lib/contract/constructorMethods.js:132:56)
    at Function.deployed (/Users/benjamindiamond/anonymous-zether/packages/protocol/node_modules/@truffle/contract/lib/contract/constructorMethods.js:84:16)
    at repl:1:5
    at Script.runInThisContext (vm.js:131:20)
    at REPLServer.defaultEval (repl.js:432:29)
    at bound (domain.js:429:14)
    at REPLServer.runBound [as eval] (domain.js:442:12)
    at REPLServer.onLine (repl.js:759:10)
    at REPLServer.emit (events.js:327:22)
    at REPLServer.EventEmitter.emit (domain.js:485:12)
    at REPLServer.Interface._onLine (readline.js:337:10)
    at REPLServer.Interface._line (readline.js:666:8)
    at REPLServer.Interface._ttyWrite (readline.js:1006:14)
    at REPLServer.self._ttyWrite (repl.js:850:9)
    at ReadStream.onkeypress (readline.js:213:10)
(node:52653) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```
any thoughts on this? i haven't worked on this stuff in a while so i'm probably missing some obvious things. thanks again.

**Comment by JohnSt99** [comment]
Thank you for your rapid response! I have ganache running on 9545 using `ganache-cli --gasPrice 0 -p 9545` .
The changes look good! Me and my colleagues will continue to contribute if anything comes to mind while we test the project.

Maybe change all the port numbers to 8545 instead.

**Comment by benediamond** [comment]
cool. merged. keep me posted if anything comes to mind! also happy to help. thanks again.

**Pull request merged**
